all:	infinite alarmClock clock showCmdArg stringTokenizer

infinite: infinite.c
	gcc -Wall -o infinite infinite.c

alarmClock: alarmClock.c
	gcc -Wall -o alarmClock alarmClock.c

clock:	clock.c
	gcc -Wall -o clock clock.c

showCmdArg:	showCmdArg.c
	gcc -Wall -o showCmdArg showCmdArg.c

stringTokenizer:	stringTokenizer.c
	gcc -Wall -o stringTokenizer stringTokenizer.c

clean:
	rm -f infinite alarmClock clock showCmdArg stringTokenizer
